### ISSUE TITLE
proposal: New Userflow

### ISSUE THREAD

**Issue by lassediercks** [hundekoerper/slackodoro#16]
This is a proposal for a new userflow

First thing a user sees is the prompt to connect with a slack workspace. Cause that's what slackodoro is about. There are enough timers without that :D 

![tablet copy 2](https://user-images.githubusercontent.com/1765584/30521608-6105b452-9bc2-11e7-8bfc-bff59d51df67.png)

After the user connected to a workspace slackodoro comes with a input for the task (main purpose).

It's possible to toggle it and to disconnect from the worksspace via the settings

![tablet](https://user-images.githubusercontent.com/1765584/30521618-8216f930-9bc2-11e7-9198-83c1fef5ce4e.png)

------

purpose of this issue is to document & discuss this idea and to agree or disagree upon it.

------

ptal @hundekoerper

**Comment by hundekoerper** [comment]
I like it.

One thing though: despite enough timers being out there to simply track the time, I would still give the user the option to use the bare bones timer.

**Comment by lassediercks** [comment]
@hundekoerper I disagree. 

With putting the slack connection in the first place we focus on the idea and value.
It deserves more than being an opt-it feature :D

**Comment by hundekoerper** [comment]
@lassediercks 

I don't think such a fallback would devalue the core functionality to an opt-in feature. People come for the main feature sure, but there is no reason to punish those who just want to use the the lesser functionality as they are using the application either way. Besides that any problems with Slack would render the application useless, which is a problem when additional features (e.g. GitHub integration) are introduced.

**Comment by lassediercks** [comment]
@hundekoerper 

I do agree. 

Propsal: 
![tablet copy 2](https://user-images.githubusercontent.com/1765584/30540610-1979aeca-9c78-11e7-9a78-2bf03d095a3e.png)

**Comment by hundekoerper** [comment]
yes that's what I had in mind

**Comment by lassediercks** [comment]
hachja
